<a href="https://colab.research.google.com/github/mukulsingh94868/ML-project/blob/supervisedML/Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
# loading 
df=pd.read_csv("http://13.234.66.67/summer19/datasets/bank.csv")

In [3]:
# schema
df.info

<bound method DataFrame.info of       RowNumber  CustomerId  ... EstimatedSalary  Exited
0             1    15634602  ...       101348.88       1
1             2    15647311  ...       112542.58       0
2             3    15619304  ...       113931.57       1
3             4    15701354  ...        93826.63       0
4             5    15737888  ...        79084.10       0
5             6    15574012  ...       149756.71       1
6             7    15592531  ...        10062.80       0
7             8    15656148  ...       119346.88       1
8             9    15792365  ...        74940.50       0
9            10    15592389  ...        71725.73       0
10           11    15767821  ...        80181.12       0
11           12    15737173  ...        76390.01       0
12           13    15632264  ...        26260.98       0
13           14    15691483  ...       190857.79       0
14           15    15600882  ...        65951.65       0
15           16    15643966  ...        64327.26       0

In [4]:
# schema
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [0]:
# removing data
features=df.iloc[:,3:13].values

In [6]:
features

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
features.shape

(10000, 10)

In [0]:
# finding label
label=df.iloc[:,13].values

In [9]:
label.shape

(10000,)

In [0]:
# label encoding
from sklearn.preprocessing   import LabelEncoder,OneHotEncoder

In [0]:
# --
lbc=LabelEncoder()

In [0]:
# for geo
features[:,1]=lbc.fit_transform(features[:,1])

In [0]:
# gender
features[:,2]=lbc.fit_transform(features[:,2])

In [14]:
features

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
# creating dummy variables
one=OneHotEncoder(categorical_features=[1])

In [16]:
# apply
features=one.fit_transform(features).toarray()
features1=features[:,1:]

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [17]:
# checking columns
features1.shape

(10000, 11)

In [0]:
# training and testing
from sklearn.model_selection   import train_test_split

In [0]:
X,x,Y,y=train_test_split(features1,label,test_size=0.2)

In [0]:
# feature scaling
from sklearn.preprocessing   import StandardScaler

In [0]:
sc=StandardScaler()

In [0]:
# training data scale
X=sc.fit_transform(X)

In [0]:
# testing data transform
x=sc.transform(x)

In [32]:
# X
x.shape

(2000, 11)

In [34]:
X.shape

(8000, 11)

In [0]:
# now we can create ANN model

In [37]:
import Keras   # this is the way of using tensorflow in background

ModuleNotFoundError: ignored

In [38]:
!pip3 install TensorFlow


In [42]:
!pip3 install keras


In [0]:
import keras

In [0]:
from keras.models  import Sequential

In [0]:
# filling data in each layer
from keras.layers  import Dense
# this will give the method to decide activation function and number of nodes in each layer
# including input,hidden and output layer

In [48]:
# now we can design model
model=Sequential()

W0708 10:15:16.408090 140243432605568 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [49]:
# now can web add imput layer
model.add(Dense(6,input_shape=(11,),activation="relu"))
# relu -- means  rectifier activation function

W0708 10:20:45.224885 140243432605568 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0708 10:20:45.239105 140243432605568 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [0]:
# adding one more hidden layer
model.add(Dense(6,activation='relu'))
# note we don't have to assign number of inputs after first/input layer

In [0]:
# final layer adding 
model.add(Dense(1,activation='sigmoid'))

In [53]:
# compile
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
#  optimizer -- weight adjust method  -- stochastic  g d (adam)

W0708 10:34:39.998919 140243432605568 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0708 10:34:40.039463 140243432605568 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0708 10:34:40.049354 140243432605568 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [54]:

# training data fit
model.fit(X,Y,batch_size=2000,epochs=100)

W0708 10:38:56.226013 140243432605568 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.5772 - acc: 0.7957
Epoch 2/100
8000/8000 [==============================] - 0s 2us/step - loss: 0.5715 - acc: 0.7958
Epoch 3/100
8000/8000 [==============================] - 0s 2us/step - loss: 0.5655 - acc: 0.7957
Epoch 4/100
8000/8000 [==============================] - 0s 3us/step - loss: 0.5599 - acc: 0.7957
Epoch 5/100
8000/8000 [==============================] - 0s 2us/step - loss: 0.5544 - acc: 0.7957
Epoch 6/100
8000/8000 [==============================] - 0s 2us/step - loss: 0.5492 - acc: 0.7957
Epoch 7/100
8000/8000 [==============================] - 0s 2us/step - loss: 0.5444 - acc: 0.7958
Epoch 8/100
8000/8000 [==============================] - 0s 2us/step - loss: 0.5396 - acc: 0.7958
Epoch 9/100
8000/8000 [==============================] - 0s 2us/step - loss: 0.5352 - acc: 0.7958
Epoch 10/100
8000/8000 [==============================] - 0s 2us/step - loss: 0.5309 - acc: 0.7957
Epoch 11/100
8000/

In [55]:
model.predict(x)    # now prediction test data

array([[0.01981822],
       [0.20722935],
       [0.01149392],
       ...,
       [0.08084449],
       [0.23852885],
       [0.06665668]], dtype=float32)